/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { Vector3 } from "@react-three/fiber";
;

const arrow_pos =  new THREE.Vector3(0);
const arrow_offset = new THREE.Vector3(0, 0.018, -0.039);
const bow_offset = new THREE.Vector3(0, 0.139, -0.038);

type GLTFResult = GLTF & {
    nodes: {
        Mesh_weapon_ballista: THREE.Mesh;
        Mesh_weapon_ballista_1: THREE.Mesh;
        bow: THREE.Mesh;
        Mesh_arrow: THREE.Mesh;
        Mesh_arrow_1: THREE.Mesh;
    };
    materials: {
        stone: THREE.MeshStandardMaterial;
        wood: THREE.MeshStandardMaterial;
    };
};

type ArrowTowerModelProps = JSX.IntrinsicElements["group"] & {
    arrow_position: [number,number,number];
};

export function ArrowTowerModel(props: ArrowTowerModelProps) {
    const { nodes, materials } = useGLTF("assets/tower-defense-kit/weapon_ballista.glb") as GLTFResult;

    arrow_pos.fromArray(props.arrow_position)
    arrow_pos.add(arrow_offset);

    return (
        <group {...props} dispose={null} scale={1}>
            <group scale={2} position={[0, 0.5, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh_weapon_ballista.geometry}
                    material={materials.stone}
                    scale={1}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Mesh_weapon_ballista_1.geometry}
                    material={materials.wood}
                    scale={1}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.bow.geometry}
                    material={materials.wood}
                    position={bow_offset}
                    scale={0.5}
                >
                    <group position={arrow_offset} scale={[1, 1, 0.5]}>
                        <mesh castShadow receiveShadow geometry={nodes.Mesh_arrow.geometry} material={materials.wood} />
                        <mesh
                            castShadow
                            receiveShadow
                            geometry={nodes.Mesh_arrow_1.geometry}
                            material={materials.stone}
                        />
                    </group>
                </mesh>
            </group>
        </group>
    );
}

useGLTF.preload("assets/tower-defense-kit/weapon_ballista.glb");
